name: Auto PR - Submission
on:
  push:
    branches:
      - tool/*

permissions:
  pull-requests: write
  
jobs:
  pull-request:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Open or update PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh_pr_up() { IFS=$'\n'; gh pr create $* || gh pr edit $*; }
        gh_pr_up --title "🚀 New tool review request" --label "needs-tool-review" --draft